"use strict";
"use client";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageHeader = PageHeader;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const NotificationBell_1 = require("@/components/notifications/NotificationBell");
function PageHeader({ title, subtitle, badge, compact = false, action, secondaryAction, tabs, toolbar, meta, search, }) {
    return ((0, jsx_runtime_1.jsx)("header", { className: "sticky top-0 z-30 shrink-0 border-b border-brand-line-strong/50 bg-white", children: (0, jsx_runtime_1.jsxs)("div", { className: compact ? "px-6 py-3 lg:px-8" : "px-6 py-4 lg:px-8", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between gap-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex min-w-0 flex-1 items-center gap-3", children: [(0, jsx_runtime_1.jsx)("span", { className: "hidden h-8 w-1 shrink-0 rounded-full bg-gradient-to-b from-brand-signature to-brand-blue/40 sm:block", "aria-hidden": true }), (0, jsx_runtime_1.jsxs)("div", { className: "min-w-0", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex min-w-0 flex-wrap items-baseline gap-x-2.5 gap-y-0.5", children: [(0, jsx_runtime_1.jsx)("h1", { className: compact
                                                        ? "truncate text-[22px] font-bold tracking-[-0.04em] text-brand-ink"
                                                        : "truncate text-[26px] font-bold tracking-[-0.04em] text-brand-ink", children: title }), badge ? ((0, jsx_runtime_1.jsx)("span", { className: "shrink-0 rounded-lg bg-brand-blue-soft/55 px-2 py-0.5 text-[11px] font-semibold tabular-nums text-brand-signature ring-1 ring-inset ring-brand-blue/20", children: badge })) : null] }), subtitle ? ((0, jsx_runtime_1.jsx)("p", { className: compact
                                                ? "mt-0.5 text-[12px] leading-snug text-brand-ink-tertiary"
                                                : "mt-1 text-[13px] leading-relaxed text-brand-ink-tertiary", children: subtitle })) : null] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex shrink-0 items-center gap-2.5", children: [search ? ((0, jsx_runtime_1.jsxs)("div", { className: "relative hidden md:block", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Search, { className: "absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-brand-ink-tertiary", strokeWidth: 2 }), (0, jsx_runtime_1.jsx)("input", { type: "search", value: search.value, onChange: (event) => search.onChange(event.target.value), placeholder: search.placeholder ?? "Search...", "aria-label": search.placeholder ?? "Search", className: "h-9 w-48 rounded-xl border border-brand-line/50 bg-white/80 pl-9 pr-3 text-[13px] text-brand-ink outline-none ring-0 transition placeholder:text-brand-ink-tertiary focus:border-brand-blue/45 focus:bg-white focus:ring-2 focus:ring-brand-blue/15 lg:w-56" })] })) : null, (0, jsx_runtime_1.jsx)(NotificationBell_1.NotificationBell, {}), action || secondaryAction ? ((0, jsx_runtime_1.jsx)("span", { className: "hidden h-6 w-px bg-brand-line/50 sm:block", "aria-hidden": true })) : null, secondaryAction ? ((0, jsx_runtime_1.jsxs)("button", { type: "button", onClick: secondaryAction.onClick, className: "flex h-9 items-center gap-1.5 rounded-xl bg-brand-orange px-4 text-[13px] font-semibold text-white shadow-sm transition hover:bg-brand-orange-hover hover:shadow-md", children: [secondaryAction.showPlus !== false ? ((0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "h-4 w-4", strokeWidth: 2.5 })) : null, (0, jsx_runtime_1.jsx)("span", { className: "hidden sm:inline", children: secondaryAction.label })] })) : null, action ? ((0, jsx_runtime_1.jsxs)("button", { type: "button", onClick: action.onClick, className: "flex h-9 items-center gap-1.5 rounded-xl bg-brand-orange px-4 text-[13px] font-semibold text-white shadow-sm transition hover:bg-brand-orange-hover hover:shadow-md", children: [action.showPlus !== false ? ((0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "h-4 w-4", strokeWidth: 2.5 })) : null, (0, jsx_runtime_1.jsx)("span", { className: "hidden sm:inline", children: action.label })] })) : null] })] }), tabs ? (0, jsx_runtime_1.jsx)("div", { className: "mt-4 -mb-px", children: tabs }) : null, toolbar || meta ? ((0, jsx_runtime_1.jsxs)("div", { className: compact ? "mt-4" : "mt-5", children: [toolbar ? (0, jsx_runtime_1.jsx)("div", { className: "min-w-0", children: toolbar }) : null, meta ? (0, jsx_runtime_1.jsx)("div", { className: toolbar ? "mt-3" : undefined, children: meta }) : null] })) : ((0, jsx_runtime_1.jsx)("div", { className: "h-0", "aria-hidden": true }))] }) }));
}
