"""initial_schema

Revision ID: c37abb0651e4
Revises: 
Create Date: 2026-09-05 02:09:26.415352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37abb0651e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legacy_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=True)
    op.create_index(op.f('ix_discount_codes_legacy_id'), 'discount_codes', ['legacy_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legacy_id', sa.String(), nullable=True),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('cheer_form_subtype', sa.String(), nullable=True),
    sa.Column('dance_form_subtype', sa.String(), nullable=True),
    sa.Column('school_program_name', sa.String(), nullable=True),
    sa.Column('school_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('zip_postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('coach_name', sa.String(), nullable=True),
    sa.Column('coach_phone', sa.String(), nullable=True),
    sa.Column('coach_email', sa.String(), nullable=True),
    sa.Column('billing_person_name', sa.String(), nullable=True),
    sa.Column('billing_person_email', sa.String(), nullable=True),
    sa.Column('choreographer_name', sa.String(), nullable=True),
    sa.Column('choreographer_email', sa.String(), nullable=True),
    sa.Column('number_of_copies', sa.String(), nullable=True),
    sa.Column('package_type', sa.String(), nullable=True),
    sa.Column('requested_editor', sa.String(), nullable=True),
    sa.Column('time_length_of_mix', sa.String(), nullable=True),
    sa.Column('music_affiliate', sa.String(), nullable=True),
    sa.Column('power_music_covers', sa.Text(), nullable=True),
    sa.Column('routine_notes', sa.Text(), nullable=True),
    sa.Column('custom_voiceovers', sa.Text(), nullable=True),
    sa.Column('gym_name', sa.String(), nullable=True),
    sa.Column('gym_billing_address', sa.Text(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('team_coed_all_girl', sa.String(), nullable=True),
    sa.Column('team_colors', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('school_billing_address', sa.Text(), nullable=True),
    sa.Column('mascot', sa.String(), nullable=True),
    sa.Column('split_or_no_split', sa.String(), nullable=True),
    sa.Column('viroc_choreographer_name', sa.String(), nullable=True),
    sa.Column('viroc_choreographer_email', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('coach_contact_full_name', sa.String(), nullable=True),
    sa.Column('coach_email_address', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('sending_eight_count_sheets', sa.String(), nullable=True),
    sa.Column('using_eight_count_sheets', sa.String(), nullable=True),
    sa.Column('song_list_suggestions', sa.Text(), nullable=True),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('how_did_you_find_out', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('package', sa.String(), nullable=False),
    sa.Column('music_theme', sa.Text(), nullable=True),
    sa.Column('editor_request', sa.String(), nullable=True),
    sa.Column('requested_producer', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_compliance', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('attention_reason', sa.Text(), nullable=True),
    sa.Column('is_past_order', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_legacy_id'), 'orders', ['legacy_id'], unique=False)
    op.create_table('package_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_prices_package_key'), 'package_prices', ['package_key'], unique=True)
    op.create_table('producers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legacy_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initials', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('mixes_this_week', sa.Integer(), nullable=False),
    sa.Column('next_available', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('work_days', sa.JSON(), nullable=False),
    sa.Column('max_mixes_per_day', sa.Integer(), nullable=True),
    sa.Column('overtime_days', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_initials'), 'producers', ['initials'], unique=True)
    op.create_index(op.f('ix_producers_legacy_id'), 'producers', ['legacy_id'], unique=False)
    op.create_table('secret_menu_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('menu_title', sa.String(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_song_tiers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mtd_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legacy_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('assigned_producer_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('editor_request', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('editor_initials', sa.String(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('package', sa.String(), nullable=False),
    sa.Column('music_theme', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_compliance', sa.String(), nullable=False),
    sa.Column('invoice', sa.String(), nullable=False),
    sa.Column('mix_start_date', sa.Date(), nullable=True),
    sa.Column('mix_end_date', sa.Date(), nullable=True),
    sa.Column('waiting_on', sa.String(), nullable=True),
    sa.Column('eight_count_sheet', sa.String(), nullable=False),
    sa.Column('have_songs', sa.String(), nullable=False),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('record_status', sa.String(), nullable=True),
    sa.Column('in_payroll', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_producer_id'], ['producers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mtd_records_assigned_producer_id'), 'mtd_records', ['assigned_producer_id'], unique=False)
    op.create_index(op.f('ix_mtd_records_legacy_id'), 'mtd_records', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_mtd_records_order_id'), 'mtd_records', ['order_id'], unique=False)
    op.create_table('producer_time_off',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_time_off_producer_id'), 'producer_time_off', ['producer_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producer_id', sa.UUID(), nullable=True),
    sa.Column('producer_initials', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_entries_day'), 'schedule_entries', ['day'], unique=False)
    op.create_index(op.f('ix_schedule_entries_producer_id'), 'schedule_entries', ['producer_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_producer_initials'), 'schedule_entries', ['producer_initials'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_entries_producer_initials'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_producer_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_day'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_producer_time_off_producer_id'), table_name='producer_time_off')
    op.drop_table('producer_time_off')
    op.drop_index(op.f('ix_mtd_records_order_id'), table_name='mtd_records')
    op.drop_index(op.f('ix_mtd_records_legacy_id'), table_name='mtd_records')
    op.drop_index(op.f('ix_mtd_records_assigned_producer_id'), table_name='mtd_records')
    op.drop_table('mtd_records')
    op.drop_table('secret_menu_pricing')
    op.drop_index(op.f('ix_producers_legacy_id'), table_name='producers')
    op.drop_index(op.f('ix_producers_initials'), table_name='producers')
    op.drop_table('producers')
    op.drop_index(op.f('ix_package_prices_package_key'), table_name='package_prices')
    op.drop_table('package_prices')
    op.drop_index(op.f('ix_orders_legacy_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_discount_codes_legacy_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_table('discount_codes')
    # ### end Alembic commands ###
