"""add_payroll_fields_to_mtd_records

Revision ID: e83912ccaaae
Revises: b9c0d1e2f3a4
Create Date: 2026-09-12 13:04:36.049689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83912ccaaae'
down_revision: Union[str, Sequence[str], None] = 'b9c0d1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('addon_rules_addon_id_key'), 'addon_rules', type_='unique')
    op.drop_index(op.f('ix_addon_rules_addon_id'), table_name='addon_rules')
    op.create_index(op.f('ix_addon_rules_addon_id'), 'addon_rules', ['addon_id'], unique=True)
    op.drop_constraint(op.f('compliant_affiliates_name_key'), 'compliant_affiliates', type_='unique')
    op.drop_index(op.f('ix_compliant_affiliates_name'), table_name='compliant_affiliates')
    op.create_index(op.f('ix_compliant_affiliates_name'), 'compliant_affiliates', ['name'], unique=True)
    op.add_column('mtd_records', sa.Column('system_calculated_customer_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('mtd_records', sa.Column('final_customer_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('mtd_records', sa.Column('final_customer_price_overridden', sa.Boolean(), nullable=False))
    op.add_column('mtd_records', sa.Column('pricing_breakdown', sa.Text(), nullable=True))
    op.add_column('mtd_records', sa.Column('rate_used', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('mtd_records', sa.Column('rate_source', sa.String(), nullable=True))
    op.add_column('mtd_records', sa.Column('producer_payout', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('mtd_records', sa.Column('slt_portion', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('mtd_records', sa.Column('payroll_finalized', sa.Boolean(), nullable=False))
    op.add_column('mtd_records', sa.Column('payroll_breakdown', sa.Text(), nullable=True))
    op.drop_constraint(op.f('uq_pricing_rules_form_subtype_package'), 'pricing_rules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_pricing_rules_form_subtype_package'), 'pricing_rules', ['form_type', 'subtype_id', 'package_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('mtd_records', 'payroll_breakdown')
    op.drop_column('mtd_records', 'payroll_finalized')
    op.drop_column('mtd_records', 'slt_portion')
    op.drop_column('mtd_records', 'producer_payout')
    op.drop_column('mtd_records', 'rate_source')
    op.drop_column('mtd_records', 'rate_used')
    op.drop_column('mtd_records', 'pricing_breakdown')
    op.drop_column('mtd_records', 'final_customer_price_overridden')
    op.drop_column('mtd_records', 'final_customer_price')
    op.drop_column('mtd_records', 'system_calculated_customer_price')
    op.drop_index(op.f('ix_compliant_affiliates_name'), table_name='compliant_affiliates')
    op.create_index(op.f('ix_compliant_affiliates_name'), 'compliant_affiliates', ['name'], unique=False)
    op.create_unique_constraint(op.f('compliant_affiliates_name_key'), 'compliant_affiliates', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_addon_rules_addon_id'), table_name='addon_rules')
    op.create_index(op.f('ix_addon_rules_addon_id'), 'addon_rules', ['addon_id'], unique=False)
    op.create_unique_constraint(op.f('addon_rules_addon_id_key'), 'addon_rules', ['addon_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
