"use strict";
"use client";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeleteProducerModal = DeleteProducerModal;
const jsx_runtime_1 = require("react/jsx-runtime");
const Avatar_1 = require("@/components/ui/Avatar");
function DeleteProducerModal({ open, producer, assignedMixesCount = 0, onClose, onConfirm, }) {
    if (!open || !producer)
        return null;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "fixed inset-0 z-50 flex items-center justify-center p-4", children: [(0, jsx_runtime_1.jsx)("button", { type: "button", className: "absolute inset-0 bg-brand-scrim backdrop-blur-sm", onClick: onClose, "aria-label": "Close" }), (0, jsx_runtime_1.jsxs)("div", { role: "dialog", "aria-modal": "true", "aria-labelledby": "delete-producer-title", className: "relative w-full max-w-[360px] overflow-hidden rounded-[22px] bg-brand-elevated shadow-[0_24px_80px_rgba(0,0,0,0.28)]", children: [(0, jsx_runtime_1.jsxs)("div", { className: "px-6 pb-5 pt-7 text-center", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex justify-center", children: (0, jsx_runtime_1.jsx)(Avatar_1.Avatar, { producer: producer, size: "xl" }) }), (0, jsx_runtime_1.jsxs)("h2", { id: "delete-producer-title", className: "mt-4 text-[18px] font-semibold tracking-[-0.02em] text-brand-ink", children: ["Delete ", producer.name, "?"] }), assignedMixesCount > 0 ? ((0, jsx_runtime_1.jsxs)("div", { className: "mt-3 rounded-xl border border-amber-200 bg-amber-50/80 p-3.5 text-left", children: [(0, jsx_runtime_1.jsxs)("p", { className: "text-[13px] font-medium leading-relaxed text-amber-900", children: ["This producer already has", " ", (0, jsx_runtime_1.jsxs)("span", { className: "font-bold text-amber-950", children: [assignedMixesCount, " mix", assignedMixesCount === 1 ? "" : "es"] }), " ", "assigned to them. Are you sure you want to delete them?"] }), (0, jsx_runtime_1.jsxs)("p", { className: "mt-1.5 text-[11px] leading-snug text-amber-800/90", children: ["Existing assignments will keep ", producer.name, "'s name as read-only historical records, but ", producer.name, " will be removed from the producer roster and future scheduling."] })] })) : ((0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-[13px] leading-relaxed text-brand-ink-secondary", children: "This removes them from the producer roster and future assignments. You can add them again later if needed." }))] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col border-t border-black/[0.08]", children: [(0, jsx_runtime_1.jsx)("button", { type: "button", onClick: onConfirm, className: "border-b border-black/[0.08] py-3.5 text-[15px] font-semibold text-brand-danger transition hover:bg-brand-orange-soft/60", children: "Delete Producer" }), (0, jsx_runtime_1.jsx)("button", { type: "button", onClick: onClose, className: "py-3.5 text-[15px] font-medium text-brand-ink transition hover:bg-brand-bg", children: "Cancel" })] })] })] }));
}
