"use strict";
"use client";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SchedulePageToolbar = SchedulePageToolbar;
const jsx_runtime_1 = require("react/jsx-runtime");
const clsx_1 = __importDefault(require("clsx"));
const OrderFormFilters_1 = require("@/components/orders/OrderFormFilters");
const FilterPill_1 = require("@/components/ui/FilterPill");
const ProducerSelect_1 = require("@/components/ui/ProducerSelect");
const ScheduleHeaderMeta_1 = require("@/components/schedule/ScheduleHeaderMeta");
const ScheduleStatusFilterPanel_1 = require("@/components/schedule/ScheduleStatusFilterPanel");
function FilterGroup({ label, children, className, }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: (0, clsx_1.default)("flex min-w-0 flex-col gap-1.5", className), children: [(0, jsx_runtime_1.jsx)("p", { className: "px-0.5 text-[10px] font-semibold uppercase tracking-[0.08em] text-brand-ink-tertiary", children: label }), (0, jsx_runtime_1.jsx)("div", { className: "inline-flex max-w-full flex-wrap items-center gap-0.5 rounded-xl bg-white p-1 shadow-sm ring-1 ring-inset ring-brand-line/45", role: "group", "aria-label": label, children: children })] }));
}
function SchedulePageToolbar({ form, cheerSubtype, danceSubtype, formCounts, cheerCounts, danceCounts, view, statusFilter, columns, availableCount, offToday, totalProducers, producers, selectedEditor = "all", onEditorChange, onFormChange, onCheerSubtypeChange, onDanceSubtypeChange, onViewChange, onStatusFilterChange, }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col gap-3.5", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col gap-3.5 lg:flex-row lg:items-center lg:justify-between", role: "toolbar", "aria-label": "Schedule filters", children: [(0, jsx_runtime_1.jsxs)("div", { className: "relative z-40 inline-flex flex-wrap items-center gap-0.5 rounded-xl bg-brand-elevated/80 p-0.5 ring-1 ring-inset ring-brand-line/40", children: [(0, jsx_runtime_1.jsx)(OrderFormFilters_1.OrderFormFilters, { grouped: true, portalMenus: true, form: form, cheerSubtype: cheerSubtype, danceSubtype: danceSubtype, onFormChange: onFormChange, onCheerSubtypeChange: onCheerSubtypeChange, onDanceSubtypeChange: onDanceSubtypeChange, formCounts: formCounts, cheerCounts: cheerCounts, danceCounts: danceCounts }), (0, jsx_runtime_1.jsx)("span", { className: "mx-0.5 hidden h-5 w-px shrink-0 bg-brand-line/45 sm:block", "aria-hidden": true }), (0, jsx_runtime_1.jsx)(ScheduleStatusFilterPanel_1.ScheduleStatusFilterPanel, { grouped: true, value: statusFilter, onChange: onStatusFilterChange }), producers && producers.length > 0 && onEditorChange ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("span", { className: "mx-0.5 hidden h-5 w-px shrink-0 bg-brand-line/45 sm:block", "aria-hidden": true }), (0, jsx_runtime_1.jsx)("div", { className: "px-1.5 py-0.5", children: (0, jsx_runtime_1.jsx)(ProducerSelect_1.ProducerSelect, { producers: producers, value: selectedEditor, onChange: onEditorChange, label: "Editor:", allLabel: "All Editors" }) })] })) : null] }), (0, jsx_runtime_1.jsx)("div", { className: "flex shrink-0 flex-wrap items-center gap-2.5", children: (0, jsx_runtime_1.jsxs)(FilterGroup, { label: "Range", children: [(0, jsx_runtime_1.jsx)(FilterPill_1.FilterPill, { label: "Today", active: view === "today", variant: "grouped", onClick: () => onViewChange("today") }), (0, jsx_runtime_1.jsx)(FilterPill_1.FilterPill, { label: "This Week", active: view === "week", variant: "grouped", onClick: () => onViewChange("week") }), (0, jsx_runtime_1.jsx)(FilterPill_1.FilterPill, { label: "This Month", active: view === "month", variant: "grouped", onClick: () => onViewChange("month") }), (0, jsx_runtime_1.jsx)(FilterPill_1.FilterPill, { label: "90 Day", active: view === "90days", variant: "grouped", onClick: () => onViewChange("90days") }), (0, jsx_runtime_1.jsx)(FilterPill_1.FilterPill, { label: "6 Month", active: view === "6months", variant: "grouped", onClick: () => onViewChange("6months") })] }) })] }), (0, jsx_runtime_1.jsx)("div", { className: "border-t border-brand-line/30 px-1 pt-3.5", children: (0, jsx_runtime_1.jsx)(ScheduleHeaderMeta_1.ScheduleHeaderMeta, { columns: columns, availableCount: availableCount, offToday: offToday, totalProducers: totalProducers, view: view }) })] }));
}
