"use strict";
"use client";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MTDPageToolbar = MTDPageToolbar;
const jsx_runtime_1 = require("react/jsx-runtime");
const OrderFormFilters_1 = require("@/components/orders/OrderFormFilters");
const MTDTableFilters_1 = require("@/components/mtd/MTDTableFilters");
function MTDPageToolbar({ form, cheerSubtype, danceSubtype, onFormChange, onCheerSubtypeChange, onDanceSubtypeChange, formCounts, cheerCounts, danceCounts, records, producers, orderById, filters, onFiltersChange, onFiltersReset, onPricingClick, }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-2.5", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-wrap items-center gap-2.5", children: [(0, jsx_runtime_1.jsxs)("div", { className: "inline-flex flex-wrap items-center gap-0.5 rounded-xl bg-brand-elevated/80 p-0.5 ring-1 ring-inset ring-brand-line/40", role: "toolbar", "aria-label": "MTD filters", children: [(0, jsx_runtime_1.jsx)(OrderFormFilters_1.OrderFormFilters, { grouped: true, form: form, cheerSubtype: cheerSubtype, danceSubtype: danceSubtype, onFormChange: onFormChange, onCheerSubtypeChange: onCheerSubtypeChange, onDanceSubtypeChange: onDanceSubtypeChange, formCounts: formCounts, cheerCounts: cheerCounts, danceCounts: danceCounts }), (0, jsx_runtime_1.jsx)("span", { className: "mx-0.5 hidden h-5 w-px shrink-0 bg-brand-line/45 sm:block", "aria-hidden": true }), (0, jsx_runtime_1.jsx)(MTDTableFilters_1.MTDTableFilterPanel, { grouped: true, records: records, producers: producers, orderById: orderById, filters: filters, onChange: onFiltersChange, onReset: onFiltersReset, form: form })] }), onPricingClick ? ((0, jsx_runtime_1.jsx)("button", { type: "button", onClick: onPricingClick, className: "ml-auto inline-flex h-8 shrink-0 items-center rounded-lg bg-brand-orange px-3.5 text-[12px] font-semibold text-white shadow-[0_1px_2px_rgba(0,0,0,0.08)] transition hover:bg-brand-orange-hover hover:shadow-[0_2px_4px_rgba(0,0,0,0.12)]", children: "Pricing" })) : null] }), (0, jsx_runtime_1.jsx)(MTDTableFilters_1.MTDFilterChipsRow, { records: records, producers: producers, orderById: orderById, filters: filters, onChange: onFiltersChange, onReset: onFiltersReset, form: form })] }));
}
